version: '3'

services:
  phapp:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: phapp:123
    ports:
      - "8080:80"
    volumes:
      - "./:/var/www/html"
    container_name: my-php-app